# 今回使うDockerの参照元のイメージ
FROM ruby:3.3.6

# 環境変数の設定（ロケールとタイムゾーン）
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# Node.jsとYarnのインストールに必要なパッケージを追加し、リポジトリキーとソースを設定
RUN apt-get update -qq \
&& apt-get install -y ca-certificates curl gnupg \
&& mkdir -p /etc/apt/keyrings \
&& curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
&& NODE_MAJOR=20 \
&& echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
&& wget --quiet -O - /tmp/pubkey.gpg https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
&& echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

# 必要なパッケージ（Node.js、Yarn、ビルドツール、PostgreSQL用ライブラリ、vimなど）をインストール
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs yarn vim

# アプリケーション用ディレクトリの作成と作業ディレクトリの設定
RUN mkdir /myapp
WORKDIR /myapp

# Bundlerのインストール
RUN gem install bundler

# カレントディレクトリの内容（ホスト側）をコンテナ内の/myappにコピー
COPY . /myapp